### ISSUE TITLE
Create dummy gmail users

### ISSUE THREAD

**Issue by Muhamedkaric** [Muhamedkaric/GmailProjekat#3]
create new file "users.js" in folder scripts. 
Create array of user objects in that file. 
Object properties are: 
-id: number,
-firstName: string,
-lastName: string,
-email: string,
-password: string,
-dateOfBirth: Date.
-accountCreated: Date

5 users would be enough.
Use dummy data or our data.
In future, surely, there should be some additional properties.

**Comment by Muhamedkaric** [comment]
@nedimmujcinovic leave comment when you are finished

**Comment by nedimmujcinovic** [comment]
@Muhamedkaric   Done!

**Comment by Muhamedkaric** [comment]
@nedimmujcinovic main-script.js is commited. Why??????????????
