### ISSUE TITLE
Log in page.

### ISSUE THREAD

**Issue by Muhamedkaric** [Muhamedkaric/GmailProjekat#4]
Create log in page like this in picture below.
Firstly you need "logInPage.html" file in project.
Google label should be link to www.google.com
Don't waste time for input style. You can use some styles from bootstrap or materialUI
Please let it be symmetric.
Buttons and inputs are disabled for now.
This box from image that i provide, should be centered on screen.

![image](https://user-images.githubusercontent.com/36570905/77855110-b28d9600-71ee-11ea-9ce5-351f40287c36.png)

**Comment by Muki1008** [comment]
Done, probably

**Comment by Muhamedkaric** [comment]
Create account is also button as Next. Difference is that it has opposite style for color and background.
